/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.flurry;

import java.util.HashMap;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;

import com.flurry.android.Constants;
import com.flurry.android.FlurryAgent;

@Kroll.module(name = "Flurry", id = "ti.flurry")
public class FlurryModule extends KrollModule {
	public static String LCAT = "FlurryModule";

	// Begin Public Lifecycle

	@Kroll.method
	public void initialize(String apiKey) {
		FlurryAgent.onStartSession(getActivity(), apiKey);
	}

	// End Public Lifecycle

	// Begin Public Properties

	@Kroll.setProperty
	@Kroll.method
	public void setUserID(String value) {
		FlurryAgent.setUserId(value);
	}

	@Kroll.setProperty
	@Kroll.method
	public void setUserId(String value) {
		setUserID(value);
	}

	@Kroll.setProperty
	@Kroll.method
	public void setAge(int value) {
		FlurryAgent.setAge(value);
	}

	@Kroll.setProperty
	@Kroll.method
	public void setGender(String value) {
		FlurryAgent.setGender(value.toLowerCase().equals("m") ? Constants.MALE : Constants.FEMALE);
	}

	@Kroll.setProperty
	@Kroll.method
	public void setDebugLogEnabled(Boolean value) {
		FlurryAgent.setLogEnabled(value);
	}

	@Kroll.setProperty
	@Kroll.method
	public void setEventLoggingEnabled(Boolean value) {
		FlurryAgent.setLogEvents(value);
	}

	@Kroll.setProperty
	@Kroll.method
	public void setReportOnClose(Boolean value) {
		Log.e(LCAT, "Flurry's SDK does not expose reportOnClose on Android yet!");
	}

	@Kroll.setProperty
	@Kroll.method
	public void setSessionReportsOnPauseEnabled(Boolean value) {
		Log.e(LCAT, "Flurry's SDK does not expose sessionReportsOnPauseEnabled on Android yet!");
	}

	@Kroll.setProperty
	@Kroll.method
	public void setSecureTransportEnabled(Boolean value) {
		FlurryAgent.setUseHttps(value);
	}

	// End Public Properties

	// Start Public Methods

	@Kroll.method
	@SuppressWarnings({ "rawtypes" })
	public void trackLocation(HashMap args) {
		Log.e(LCAT, "Flurry's SDK does not expose sessionReportsOnPauseEnabled on Android yet!");
		// KrollDict dict = new KrollDict(args);
		// double latitude = dict.getDouble("latitude");
		// double longitude = dict.getDouble("longitude");
		// double horizontalAccuracy = dict.getDouble("horizontalAccuracy");
		// double verticalAccuracy = dict.getDouble("verticalAccuracy");
	}

	@Kroll.method
	@SuppressWarnings({ "rawtypes" })
	public void logEvent(String event, @Kroll.argument(optional = true) HashMap args) {
		if (args == null) {
			FlurryAgent.logEvent(event);
		} else {
			FlurryAgent.logEvent(event, args);
		}
	}

	@Kroll.method
	@SuppressWarnings({ "rawtypes" })
	public void logTimedEvent(String event, @Kroll.argument(optional = true) HashMap args) {
		if (args == null) {
			FlurryAgent.logEvent(event, true);
		} else {
			FlurryAgent.logEvent(event, args, true);
		}
	}

	@Kroll.method
	public void endTimedEvent(String event) {
		FlurryAgent.endTimedEvent(event);
	}

	@Kroll.method
	public void logAllPageViews() {
		Log.e(LCAT, "Flurry's SDK does not expose logAllPageViews on Android yet!");
	}

	@Kroll.method
	public void logPageView() {
		Log.e(LCAT, "Flurry's SDK does not expose logPageView on Android yet!");
	}

	// End Public Methods
}
